console.log("Creditz ProveKit demo target");
console.log("");
console.log("1. Install Noir/Nargo and ProveKit from the official docs.");
console.log("2. cd circuits/credit_spend");
console.log("3. cp Prover.toml.example Prover.toml");
console.log("4. nargo check");
console.log("5. Use ProveKit to compile the Noir circuit to R1CS, generate a proof, and verify it.");
console.log("");
console.log("The app accepts mode=demo-keccak for local UX.");
console.log("For mode=provekit, submit a proof envelope with:");
console.log("- scheme: provekit-noir-credit-spend-v1");
console.log("- circuit: credit_spend");
console.log("- public_inputs_hash: hash of the public spend statement");
console.log("");
console.log("Set PROVEKIT_VERIFY_BIN to an external verifier executable before accepting ProveKit proofs.");
